import type { DashboardState } from './types';

const minutesAgo = (minutes: number) =>
  new Date(Date.now() - minutes * 60_000).toISOString();

export const DEFAULT_DASHBOARD_STATE: DashboardState = {
  routines: [
    {
      id: 'sedentary',
      name: 'Time to stand',
      description: 'A gentle nudge after continuous desk presence.',
      icon: 'stand',
      enabled: true,
      every: 90,
      unit: 'minutes',
      activeStart: '09:00',
      activeEnd: '18:00',
      quietStart: '12:00',
      quietEnd: '13:00',
      interruption: 'gentle',
      contextAware: true,
    },
    {
      id: 'hydration',
      name: 'Hydration',
      description: 'Small reminders that are easy to ignore when busy.',
      icon: 'water',
      enabled: true,
      every: 60,
      unit: 'minutes',
      activeStart: '09:00',
      activeEnd: '20:00',
      quietStart: '22:00',
      quietEnd: '08:00',
      interruption: 'quiet',
      contextAware: true,
    },
    {
      id: 'food',
      name: 'Meals',
      description: 'Notice when the day is full and a meal is being missed.',
      icon: 'food',
      enabled: true,
      every: 3,
      unit: 'hours',
      activeStart: '11:30',
      activeEnd: '20:00',
      quietStart: '20:00',
      quietEnd: '11:30',
      interruption: 'gentle',
      contextAware: true,
    },
    {
      id: 'medicine',
      name: 'Medicine',
      description: 'A persistent reminder that waits for acknowledgement.',
      icon: 'medicine',
      enabled: false,
      every: 1,
      unit: 'daily',
      activeStart: '21:00',
      activeEnd: '21:30',
      quietStart: '22:00',
      quietEnd: '08:00',
      interruption: 'important',
      contextAware: false,
    },
    {
      id: 'focus-recovery',
      name: 'Focus recovery',
      description: 'Suggest a reset after an unusually fragmented work block.',
      icon: 'focus',
      enabled: false,
      every: 2,
      unit: 'hours',
      activeStart: '09:00',
      activeEnd: '18:00',
      quietStart: '12:00',
      quietEnd: '13:00',
      interruption: 'quiet',
      contextAware: true,
    },
  ],
  connections: [
    {
      id: 'calendar',
      name: 'Calendar',
      description: 'Understand your day and catch conflicting commitments.',
      icon: 'calendar',
      connected: true,
      permissions: ['Read events', 'Suggest new times', 'Edit after confirmation'],
      enabledPermissions: ['Read events', 'Suggest new times'],
      policy: 'confirm',
      statusDetail: 'Google Calendar · Demo account',
    },
    {
      id: 'email',
      name: 'Email',
      description: 'Find follow-ups and prepare drafts from desk conversations.',
      icon: 'mail',
      connected: false,
      permissions: ['Read recent threads', 'Draft replies', 'Send after confirmation'],
      enabledPermissions: ['Read recent threads', 'Draft replies'],
      policy: 'confirm',
      statusDetail: 'Not connected',
    },
    {
      id: 'slack',
      name: 'Slack',
      description: 'Keep presence aligned with what is happening at your desk.',
      icon: 'slack',
      connected: true,
      permissions: ['Read presence', 'Update presence', 'Draft messages'],
      enabledPermissions: ['Read presence', 'Update presence'],
      policy: 'automatic',
      statusDetail: 'ImpactLabs-Atl · Connected',
    },
    {
      id: 'codex',
      name: 'Codex',
      description: 'Carry task progress and attention states into the room.',
      icon: 'codex',
      connected: true,
      permissions: ['Read active task', 'Read attention state', 'Open task'],
      enabledPermissions: ['Read active task', 'Read attention state'],
      policy: 'suggest',
      statusDetail: 'Local Codex · Available',
    },
    {
      id: 'doordash',
      name: 'DoorDash',
      description: 'Prepare a meal order when your schedule leaves no gap.',
      icon: 'food',
      connected: false,
      permissions: ['View saved restaurants', 'Prepare an order', 'Open checkout'],
      enabledPermissions: ['View saved restaurants', 'Prepare an order'],
      policy: 'confirm',
      statusDetail: 'Not connected',
    },
    {
      id: 'meetings',
      name: 'Meeting apps',
      description: 'Recognize calls and create action-oriented summaries.',
      icon: 'meeting',
      connected: false,
      permissions: ['Detect active call', 'Use transcript', 'Create summary'],
      enabledPermissions: ['Detect active call', 'Create summary'],
      policy: 'suggest',
      statusDetail: 'Zoom, Meet, Teams',
    },
  ],
  privacy: {
    ambientListening: true,
    saveRawAudio: false,
    confirmMemories: true,
    activityLog: true,
    retention: '24-hours',
  },
  activity: [
    {
      id: 'initial-1',
      text: 'Slack presence changed to Available',
      detail: 'Deskemon noticed you returned to the desk.',
      timestamp: minutesAgo(12),
      tone: 'success',
    },
    {
      id: 'initial-2',
      text: 'Hydration reminder delivered',
      detail: 'Shown quietly while your calendar was free.',
      timestamp: minutesAgo(48),
      tone: 'neutral',
    },
    {
      id: 'initial-3',
      text: 'Possible commitment discarded',
      detail: 'Nothing was saved after you chose Forget.',
      timestamp: minutesAgo(83),
      tone: 'neutral',
    },
  ],
};
